version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    container_name: portfolio_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${Db_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - ./postgres:/var/lib/postgresql/data
